service: rails-portofolio
image: rails-portofolio  # Local image name (no registry prefix needed)

servers:
  web:
    hosts:
      - mokta@192.168.1.9:22
registry:
  username: moktadocker
  password: 220314rizti

builder:
  arch: arm64
env:
  secret:
    - RAILS_MASTER_KEY
